version: "3.8"

services:
  web:
    build: .
    ports:
      - "${DOCKER_HTTP_PORT}:80"
      - "${DOCKER_HTTPS_PORT}:443"
    volumes:
      - .:/var/www/html
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    container_name: laravel-craftable

  db:
    image: "mysql:5.7.31"
    ports:
      - "${DOCKER_MYSQL_PORT}:3306"
    volumes:
      - ${DOCKER_MYSQL_LOCAL_VOLUME}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
    container_name: mysql-craftable

  node:
    image: "node:14-buster"
    volumes:
      - .:/usr/app/
    working_dir: /usr/app
    stdin_open: true
    tty: true
    container_name: node-craftable

networks:
  default:
    driver: bridge
    name: craftable_default
